name: iOS CI

on:
  push:
    branches:
      - main  # Adjust as necessary
  pull_request:
    branches:
      - main  # Adjust as necessary

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Adjust as necessary

      - name: Install CocoaPods
        run: sudo gem install cocoapods
  
      - name: Install dependencies
        run: pod install

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO }}" | base64 --decode > "${GITHUB_WORKSPACE}/CrashDemoIOS/GoogleService-Info.plist"
          
      - name: Install xcpretty
        run: sudo gem install xcpretty

      - name: Apply xattr fix
        run: |
           mkdir -p /Users/runner/Library/Developer/Xcode/DerivedData/CrashDemoIOS-bkjulqkhpieqhnapaoocmywsvrya/SourcePackages/checkouts/nanopb/build
           xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/runner/Library/Developer/Xcode/DerivedData/CrashDemoIOS-bkjulqkhpieqhnapaoocmywsvrya/SourcePackages/checkouts/nanopb/build

      - name: Build and Test
        run: |
         cd ${GITHUB_WORKSPACE}/CrashDemoIOS
          ls
          xcodebuild clean build test \
            -workspace CrashDemoIOS.xcworkspace \
            -scheme CrashDemoIOS \
            -destination 'platform=iOS Simulator,name=iPhone 13' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO | xcpretty
            
      - name: Set up Node.js                               # Line 54
        uses: actions/setup-node@v2                        # Line 55
        with:                                              # Line 56
          node-version: '14'  # Ensure Node.js is installed before installing Firebase CLI # Line 57

      - name: Install Firebase CLI                         # Line 59
        run: npm install -g firebase-tools                 # Line 60

      - name: Deploy to Firebase (Optional)                # Line 62
        env:                                               # Line 63
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}    # Line 64
        run: firebase deploy --token "$FIREBASE_TOKEN"     
