name: iOS CI

on:
  push:
    branches:
      - main  # Adjust as necessary
  pull_request:
    branches:
      - main  # Adjust as necessary

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Adjust as necessary

      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: filelist
        run: | 
         echo ${GITHUB_WORKSPACE}
         ls
      - name: Install dependencies
        run: pod install

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO }}" | base64 --decode > "${GITHUB_WORKSPACE}/CrashDemoIOS/GoogleService-Info.plist"

      - name: Build and Test
        run: |
         cd ${GITHUB_WORKSPACE}/CrashDemoIOS
          ls
          xcodebuild clean build test \
            -workspace CrashDemoIOS.xcworkspace \
            -scheme CrashDemoIOS \
            -destination 'platform=iOS Simulator,name=iPhone 13' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login:ci --token "$FIREBASE_TOKEN"

      - name: Deploy to Firebase (Optional)
        run: firebase deploy --token "$FIREBASE_TOKEN"
