name: iOS CI/CD

on:
  push:
    branches:
      - main  # Adjust as necessary
  pull_request:
    branches:
      - main  # Adjust as necessary

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Adjust as necessary

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: |
          cd CrashDemoIOS
          pod install

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO }}" | base64 --decode > "${GITHUB_WORKSPACE}/CrashDemoIOS/GoogleService-Info.plist"

      - name: Install xcpretty
        run: sudo gem install xcpretty

      - name: Apply xattr fix
        run: |
           mkdir -p /Users/runner/Library/Developer/Xcode/DerivedData/CrashDemoIOS-bkjulqkhpieqhnapaoocmywsvrya/SourcePackages/checkouts/nanopb/build
           xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/runner/Library/Developer/Xcode/DerivedData/CrashDemoIOS-bkjulqkhpieqhnapaoocmywsvrya/SourcePackages/checkouts/nanopb/build

      - name: Build and Test
        run: |
          cd CrashDemoIOS
          xcodebuild clean build test \
            -workspace CrashDemoIOS.xcworkspace \
            -scheme CrashDemoIOS \
            -destination 'platform=iOS Simulator,name=iPhone 13' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Archive iOS App
        run: |
          xcodebuild clean archive -workspace CrashDemoIOS.xcworkspace -scheme CrashDemoIOS -archivePath build/CrashDemoIOS.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath "build/CrashDemoIOS.xcarchive" -exportOptionsPlist exportOptions.plist -exportPath "build"

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login:ci --token "$FIREBASE_TOKEN"

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
